version: '3'

services:

  neo4j:
    build: ./neo4j
    container_name: "graphgist-portal-neo4j"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/data:/var/lib/neo4j/data
      - ./neo4j/config:/var/lib/neo4j/conf

  api:
    build: ./api
    container_name: "graphgist-portal-api"
    ports:
      - "4001:4001"
    environment:
      - NEO4J_PASSWORD=secret
      - NEO4J_URI=bolt://neo4j:7687
    env_file:
      - ./api/.env
    links:
    - neo4j
    depends_on:
    - neo4j

  ui:
    build: ./ui-react
    container_name: "graphgist-portal-ui"
    ports:
      - "3000:3000"
    environment:
      - CI=true
      - REACT_APP_GRAPHQL_URI=http://localhost:4001/graphql
    env_file:
      - ./ui-react/.env
    links:
    - api
    depends_on:
    - api
